spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chugether
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
